name: notifying_list
description: List implementations that notify when they're modified.
version: 0.1.0
homepage: https://github.com/hacker1024/notifying_list.dart

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  meta: ^1.8.0
  collection: ^1.17.0

dev_dependencies:
  lint: ^2.0.1
